### ISSUE TITLE
RuntimeException: Unable to configure Cassandra cluster

### ISSUE THREAD

**Issue by dbadia** [wl-net/arcusplatform#5]
Hello -
I am following the instructions at 
[quickstart.md](https://github.com/wl-net/arcusplatform/blob/master/docs/quickstart.md)

Execution of ./gradlew :platform:arcus-khakis:startPlatform
fails with

> Caused by: java.lang.RuntimeException: Unable to configure Cassandra cluster, the hosts specified in cassandra.contactPoints could not be resolved

I assume this means I didn't define an environment variable or some other setting.

Full error details below
TIA
Dave

> 1) An exception was caught and reported. Message: Unable to configure Cassandra cluster, the hosts specified in cassandra.contactPoints could not be resolved
>   at com.iris.modelmanager.ModelManagerModule.configure(ModelManagerModule.java:53) (via modules: com.iris.modelmanager.ModelManagerModule -> com.iris.modelmanager.ModelManagerModule$2)
> 
> 1 error
>         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
>         at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
>         at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:225)
>         at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:327)
>         at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:394)
>         at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:348)
>         at com.iris.bootstrap.Bootstrap.bootstrap(Bootstrap.java:239)
>         ... 3 common frames omitted
> Caused by: java.lang.RuntimeException: Unable to configure Cassandra cluster, the hosts specified in cassandra.contactPoints could not be resolved
>         at com.iris.core.dao.cassandra.BaseCassandraModule.parseContactPoints(BaseCassandraModule.java:300)
>         at com.iris.core.dao.cassandra.BaseCassandraModule.configure(BaseCassandraModule.java:122)
>         at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:253)
>         at com.iris.modelmanager.ModelManagerModule.configure(ModelManagerModule.java:53)
>         at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:253)
>         at com.google.inject.spi.Elements.getElements(Elements.java:108)
>         at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:135)
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
>         ... 8 common frames omitted
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':platform:arcus-modelmanager:run-history'.
> > Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
>

**Comment by AndrewX192** [comment]
Hm,

I haven't been working off of that quickstart lately (I've been focused on https://github.com/wl-net/arcus-k8 instead, which is likely easier to get started now). Do you know if Cassandra is running (do `docker ps` to find out)? What happens if you add `127.0.0.1	cassandra.eyeris kafkaops.eyeris kairosops.eyeris kafka.eyeris` to /etc/hosts and try again?

**Comment by dbadia** [comment]
I'm going to switch over to https://github.com/wl-net/arcus-k8 since that is your focus now.  Seems it may be an easier path as well.

Just to wrap this issue up, I updated /etc/hosts, restarted the docker containers (eyeris/cassandra was running when I checked), and re-ran the gradlew command, but got the same error.   
Oh well, moving on to the arcus-k8 project

**Comment by AndrewX192** [comment]
This mode *should* work, and I have a deployment that is using it, so if you're willing to invest some time I'd encourage you to keep trying. You may need to look inside of the docker containers to see if /etc/hosts got updated appropriately. arcus-k8 is an easier way to get Arcus up, e.g. if you just want to try it out or run it in production without modifying it, but if you want to develop on Arcus you'll want to follow the quickstart. That said, I know there's a number of details that are missing from the quickstart (especially on the configuration side) which will be a hurdle.

**Comment by dbadia** [comment]
Good points.  My goal for now is to get things up and running to the point where I can re-connect to my hub to control my zigbee hose timers.  Think I read something about having to hack code to authenticate to the hub... so is the quickstart the best approach for that?

I'm willing to keep working though both approaches if it helps the project overall

**Comment by AndrewX192** [comment]
Yeah, I have a page on how to configure the hub to use Arcus, but it's not public since that page causes the hub to connect back to my Arcus deployment, which I'd rather not have happen (I don't allow signups, but it does make my debug log more noisy). If you're able to get Arcus to work I'm happy to flush out that document in a more generalized way so you can update your hub as well - it's actually a very simple process provided that you use LetsEncrypt as your certificate authority and don't mind having a flash drive plugged in.

**Comment by dbadia** [comment]
That would be great.  I've use LetsEncrypt for some of my other sites and flash drive is no problem.   Let me ask... is that possible with both the arcus-k8 approach and the quickstart approach?  Just trying to figure out which to prioritize

**Comment by AndrewX192** [comment]
Arcus on Kubernetes is a way easier way to get LetsEncrypt to work. I only did the process once for my local development setup, and I didn't document it. Once you have arcus-k8s working, then maybe you'll be able to add the missing steps for development

**Comment by AndrewX192** [comment]
Closing due to inactivity.
